In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
a = np.arange(6)

In [4]:
type(a)

numpy.ndarray

In [5]:
a

array([0, 1, 2, 3, 4, 5])

In [11]:
a2 = a[np.newaxis, :]

In [12]:
a2.shape

(1, 6)

In [13]:
a.shape

(6,)

In [14]:
 a = []

In [15]:
a = [0, 1, 2, 3, 4, 5]

In [16]:
a

[0, 1, 2, 3, 4, 5]

In [17]:
a[0]

0

In [19]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [20]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
a[2]

array([ 9, 10, 11, 12])

In [26]:
a = np.array([1, 2, 3])

In [28]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.empty(2)

array([ 5.39851764e-051, -3.19499369e+125])

In [31]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [32]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
b = np.ones(2, dtype=np.int64)

In [36]:
b

array([1, 1], dtype=int64)

In [37]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [42]:
arr = np.sort(arr)

In [43]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [45]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [47]:
x

array([[1, 2],
       [3, 4]])

In [48]:
y

array([[5, 6]])

In [49]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [51]:
array_example.ndim

3

In [53]:
array_example.size

24

In [54]:
array_example.shape

(3, 2, 4)

In [55]:
a = np.arange(6)

In [58]:
a

array([0, 1, 2, 3, 4, 5])

In [59]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [61]:
a

array([0, 1, 2, 3, 4, 5])

In [63]:
np.reshape(a, newshape=(1, 6), order='A')

array([[0, 1, 2, 3, 4, 5]])

In [68]:
a = np.array([1, 2, 3, 4, 5, 6])

In [69]:
a

array([1, 2, 3, 4, 5, 6])

In [70]:
a.shape

(6,)

In [71]:
a2 = a[np.newaxis, :]

In [72]:
a2.shape

(1, 6)

In [73]:
row_vector = a[np.newaxis, :]

In [74]:
row_vector.shape

(1, 6)

In [75]:
a[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [76]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [78]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [79]:
data = np.array([1, 2, 3])

In [80]:
data

array([1, 2, 3])

In [87]:
data[-2:]

array([2, 3])

In [88]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [89]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [91]:
b = 2

In [94]:
b > 5

False

In [93]:
if b > 5 : 
    print("에구 너무 큰데요")
else:
    print("좋아요")

좋아요


In [95]:
a[a < 5]

array([1, 2, 3, 4])

In [96]:
a >= 5

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [97]:
a[a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [100]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
a[(a > 5) | (a == 5)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [103]:
np.nonzero(a < 5)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [104]:
b = np.nonzero(a < 5)

In [106]:
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [108]:
list_of_coordinates = list(zip(b[0], b[1]))

In [109]:
list_of_coordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [110]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [111]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
arr1 = a[3:8]

In [113]:
arr1

array([4, 5, 6, 7, 8])

In [114]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [115]:
a1

array([[1, 1],
       [2, 2]])

In [116]:
a2

array([[3, 3],
       [4, 4]])

In [119]:
np.concatenate((a1, a2), axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [120]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [121]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [123]:
a = np.arange(1, 15)

In [124]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [125]:
a.reshape(2, 7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [126]:
a = np.arange(1, 15).reshape(2, 7)

In [127]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [128]:
x = np.arange(1, 25).reshape(2, 12)

In [129]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [133]:
np.hsplit(x, (3, 6, 8))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8],
        [19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [147]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [148]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [149]:
b1 = a[0,:].copy()

In [150]:
b1

array([1, 2, 3, 4])

In [151]:
b1[0] = 99

In [152]:
b1

array([99,  2,  3,  4])

In [153]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [154]:
data = np.array([1, 2])

In [155]:
ones = np.ones(2, dtype=int)

In [156]:
data

array([1, 2])

In [157]:
ones

array([1, 1])

In [158]:
data + ones

array([2, 3])

In [159]:
data - ones

array([0, 1])

In [160]:
data * ones

array([1, 2])

In [161]:
data / ones

array([1., 2.])

In [162]:
a = np.array([1, 2, 3, 4])

In [163]:
a

array([1, 2, 3, 4])

In [164]:
a.sum()

10

In [166]:
b = np.array([[1, 1], [2, 2]])

In [167]:
b

array([[1, 1],
       [2, 2]])

In [168]:
b.sum(axis=0)

array([3, 3])

In [169]:
b.sum(axis=1)

array([2, 4])

In [170]:
data = np.array([1.0, 2.0])

In [171]:
data

array([1., 2.])

In [172]:
data * 1.6

array([1.6, 3.2])

In [173]:
a

array([1, 2, 3, 4])

In [174]:
a.max()

4

In [175]:
b = np.array([[1, 4], [2, 7]])

In [176]:
b

array([[1, 4],
       [2, 7]])

In [178]:
b.min(axis=0)

array([1, 4])

In [179]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [180]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [181]:
data[0, 1]

2

In [182]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [186]:
data[0:2, 0]

array([1, 3])

In [187]:
data.max()

6

In [190]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [191]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [192]:
ones_row = np.array([[1, 1]])

In [193]:
ones_row

array([[1, 1]])

In [194]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [195]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [196]:
np.ones(3)

array([1., 1., 1.])

In [197]:
np.zeros(3)

array([0., 0., 0.])

In [198]:
rng = np.random.default_rng()

In [199]:
rng.random(3)

array([0.87509934, 0.57069616, 0.21924552])

In [200]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [201]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [202]:
rng.random((3, 2)) 

array([[0.44188252, 0.37668928],
       [0.40937344, 0.35787076],
       [0.87371045, 0.80215603]])

In [203]:
rng.integers(5, size=(2, 4)) 

array([[3, 3, 1, 2],
       [1, 3, 0, 4]], dtype=int64)

In [204]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [206]:
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

In [207]:
unique_values = np.unique(a)

In [208]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [209]:
unique_values, indices_list = np.unique(a, return_index=True)

In [210]:
indices_list

array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64)

In [211]:
unique_values, occurrence_count = np.unique(a, return_counts=True)

In [212]:
occurrence_count

array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64)

In [213]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [214]:
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [215]:
unique_values = np.unique(a_2d)

In [216]:
unique_values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [217]:
unique_rows = np.unique(a_2d, axis=0)

In [218]:
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [219]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)

In [220]:
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [221]:
indices

array([0, 1, 2], dtype=int64)

In [222]:
occurrence_count

array([2, 1, 1], dtype=int64)

In [223]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [224]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [225]:
arr = np.arange(6).reshape((2, 3))

In [226]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [227]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [228]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [230]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [231]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [232]:
reversed_arr = np.flip(arr)

In [233]:
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

In [234]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [235]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [236]:
reversed_arr = np.flip(arr_2d)

In [237]:
reversed_arr

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [238]:
reversed_arr_rows = np.flip(arr_2d, axis=0)

In [239]:
reversed_arr_rows

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [240]:
reversed_arr_columns = np.flip(arr_2d, axis=1)

In [241]:
reversed_arr_columns

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [242]:
arr_2d[1] = np.flip(arr_2d[1])

In [243]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [244]:
arr_2d[:,1] = np.flip(arr_2d[:,1])

In [245]:
arr_2d

array([[ 1, 10,  3,  4],
       [ 8,  7,  6,  5],
       [ 9,  2, 11, 12]])

In [246]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [247]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [248]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [249]:
a1 = x.flatten()
a1[0] = 99

In [250]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [251]:
a1

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [252]:
a2 = x.ravel()
a2[0] = 98

In [254]:
x

array([[98,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [255]:
a2

array([98,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])